compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"
npmAuthToken: "${NODE_AUTH_TOKEN:-node_auth_token}"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
